# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(694, 565)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.listStatus = QtWidgets.QListWidget(self.centralwidget)
        self.listStatus.setMaximumSize(QtCore.QSize(16777215, 100))
        self.listStatus.setObjectName("listStatus")
        self.gridLayout.addWidget(self.listStatus, 10, 0, 1, 2)
        self.listSimStatus = QtWidgets.QListWidget(self.centralwidget)
        self.listSimStatus.setMaximumSize(QtCore.QSize(16777215, 100))
        self.listSimStatus.setObjectName("listSimStatus")
        self.gridLayout.addWidget(self.listSimStatus, 10, 2, 1, 1)
        self.labelSimStatus = QtWidgets.QLabel(self.centralwidget)
        self.labelSimStatus.setText("")
        self.labelSimStatus.setObjectName("labelSimStatus")
        self.gridLayout.addWidget(self.labelSimStatus, 9, 2, 1, 2)
        self.labelOrgPopulation = QtWidgets.QLabel(self.centralwidget)
        self.labelOrgPopulation.setMaximumSize(QtCore.QSize(16777215, 20))
        self.labelOrgPopulation.setObjectName("labelOrgPopulation")
        self.gridLayout.addWidget(self.labelOrgPopulation, 0, 1, 1, 1)
        self.labelSelectionApproach = QtWidgets.QLabel(self.centralwidget)
        self.labelSelectionApproach.setMaximumSize(QtCore.QSize(16777215, 20))
        self.labelSelectionApproach.setObjectName("labelSelectionApproach")
        self.gridLayout.addWidget(self.labelSelectionApproach, 0, 2, 1, 1)
        self.listWidgetOrgPopulation = QtWidgets.QListWidget(self.centralwidget)
        self.listWidgetOrgPopulation.setMaximumSize(QtCore.QSize(16777215, 100))
        self.listWidgetOrgPopulation.setObjectName("listWidgetOrgPopulation")
        self.gridLayout.addWidget(self.listWidgetOrgPopulation, 3, 1, 1, 1)
        self.listWidgetSelectionApproach = QtWidgets.QListWidget(self.centralwidget)
        self.listWidgetSelectionApproach.setMaximumSize(QtCore.QSize(16777215, 100))
        self.listWidgetSelectionApproach.setObjectName("listWidgetSelectionApproach")
        self.gridLayout.addWidget(self.listWidgetSelectionApproach, 3, 2, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnStartPause = QtWidgets.QPushButton(self.centralwidget)
        self.btnStartPause.setObjectName("btnStartPause")
        self.verticalLayout.addWidget(self.btnStartPause)
        self.btnStop = QtWidgets.QPushButton(self.centralwidget)
        self.btnStop.setObjectName("btnStop")
        self.verticalLayout.addWidget(self.btnStop)
        self.gridLayout.addLayout(self.verticalLayout, 3, 0, 1, 1)
        self.canvas = QtWidgets.QWidget(self.centralwidget)
        self.canvas.setMinimumSize(QtCore.QSize(0, 167))
        self.canvas.setObjectName("canvas")
        self.gridLayout.addWidget(self.canvas, 4, 0, 6, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 694, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionOpenData = QtWidgets.QAction(MainWindow)
        self.actionOpenData.setObjectName("actionOpenData")
        self.actionGenerateTestData = QtWidgets.QAction(MainWindow)
        self.actionGenerateTestData.setObjectName("actionGenerateTestData")
        self.menuFile.addAction(self.actionOpenData)
        self.menuFile.addAction(self.actionGenerateTestData)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Genomic Selection Simulation"))
        self.labelOrgPopulation.setText(_translate("MainWindow", "Original Population"))
        self.labelSelectionApproach.setText(_translate("MainWindow", "Selection Approach"))
        self.btnStartPause.setText(_translate("MainWindow", "Start"))
        self.btnStop.setText(_translate("MainWindow", "Stop"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionOpenData.setText(_translate("MainWindow", "Open Data File"))
        self.actionGenerateTestData.setText(_translate("MainWindow", "Generate Test Data"))

